create table person(
    id varchar2(250) primary key not null,
    name varchar2(100) not null,
    lastname varchar2(100) not null,
    address varchar2(250),
    birthday date,
    type varchar2(20)
);

CREATE TABLE EXAM
(
    ID         VARCHAR2 (250) ,
    TEACHER_ID VARCHAR2 (250) ,
    TOPIC      VARCHAR2 (100) ,
    COURSE     VARCHAR2 (100) ,
    AVERAGE    NUMBER (10,2) ,
    ACTIVE     NUMBER (*,0) ,
    CREATED_AT TIMESTAMP ,
    UPDATED_AT TIMESTAMP
);


CREATE UNIQUE INDEX EXAM_PK ON EXAM(ID ASC);

ALTER TABLE EXAM
    ADD CONSTRAINT EXAM_PK PRIMARY KEY ( ID )
    USING INDEX EXAM_PK ;

CREATE TABLE EXAM_DETAIL
(
    ID         NUMBER (*,0) GENERATED ALWAYS AS IDENTITY
        ( START WITH 1 CACHE 20 ) ,
    EXAM_ID    VARCHAR2 (250) ,
    STUDENT_ID VARCHAR2 (250) ,
    SCORE      NUMBER (10,2) DEFAULT 0 ,
    OBS        VARCHAR2 (100)
);


CREATE UNIQUE INDEX EXAM_DETAIL_PK ON EXAM_DETAIL(ID ASC);

ALTER TABLE EXAM_DETAIL
    ADD CONSTRAINT EXAM_DETAIL_PK PRIMARY KEY ( ID )
    USING INDEX EXAM_DETAIL_PK ;

ALTER TABLE EXAM_DETAIL
    ADD CONSTRAINT FK_EXAM_ID FOREIGN KEY ( EXAM_ID )
        REFERENCES EXAM ( ID )
        ON DELETE CASCADE
        NOT DEFERRABLE;